module.exports = {
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  EMAIL_PASSWORD_REQUIRED: 'EMAIL_PASSWORD_REQUIRED',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  GOOGLE_ID_TOKEN_REQUIRED: 'GOOGLE_ID_TOKEN_REQUIRED',
  NOT_AUTHORISED_NO_TOKEN: 'NOT_AUTHORISED_NO_TOKEN',
  NOT_AUTHORISED_INVALID_TOKEN: 'NOT_AUTHORISED_INVALID_TOKEN',
  USER_NO_LONGER_EXISTS: 'USER_NO_LONGER_EXISTS',
  ADMIN_ACCESS_REQUIRED: 'ADMIN_ACCESS_REQUIRED',
}
